base.url=https://api.test-one-pingone.com
environment.id=465c9188-1ac6-4218-9fb8-87460383b7bc
auth.url=https://auth.test-one-pingone.com
client.id=da223f8e-a024-4a9b-8657-c72390cf289e
client.secret=***********************************
admin.console.url=https://console.test-one-pingone.com/index.html?env=465c9188-1ac6-4218-9fb8-87460383b7bc#/465c9188-1ac6-4218-9fb8-87460383b7bc/overviewDashboard
user.id=QA_USER
user.password=Ping@2026